# Generated by Django 5.2 on 2025-05-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothingitems',
            options={'verbose_name': 'clothing item', 'verbose_name_plural': 'clothing items'},
        ),
        migrations.RenameField(
            model_name='clothingitems',
            old_name='avilable',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='clothingitemsize',
            old_name='avaliable',
            new_name='available',
        ),
        migrations.AddField(
            model_name='clothingitems',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%/%d'),
        ),
    ]
